(() => {
 const SERVICE_UUID='12345678-1234-1234-1234-1234567890ab', COMMAND_UUID='12345678-1234-1234-1234-1234567890ac', TELEMETRY_UUID='12345678-1234-1234-1234-1234567890ad';
 let device=null,server=null,commandChar=null,telemetryChar=null,realConnected=false,demoTimer=null,phase=0;
 const $=id=>document.getElementById(id), dot=(id,color)=>{$(id).style.background=color;$(id).style.color=color;};
 const fmt=(n,d=2)=>Number.isFinite(n)?n.toFixed(d):'--';
 function setVal(id,v,unit='',d=2){$(id).innerHTML=`${v}<span class="unit">${unit}</span>`;}
 function setMode(real){$('navMode').textContent=real?'LIVE BLE':'DEMO MODE';dot('navDot',real?'var(--green)':'var(--yellow)');$('dataMode').innerHTML=real?'<strong>LIVE DATA</strong> · received from ESP32-C3':'<strong>DEMO DATA</strong> · not from hardware';dot('dataDot',real?'var(--green)':'var(--yellow)');if(!real){$('mpuState').textContent='MPU6050 status: demo / unknown';dot('mpuDot','var(--yellow)');}}
 function showData(d,real){if(d.ROLL!==undefined)setVal('rollVal',(d.ROLL>=0?'+':'')+fmt(d.ROLL,1),'°');if(d.PITCH!==undefined)setVal('pitchVal',(d.PITCH>=0?'+':'')+fmt(d.PITCH,1),'°');if(d.AX!==undefined)setVal('axVal',fmt(d.AX),' m/s²');if(d.AY!==undefined)setVal('ayVal',fmt(d.AY),' m/s²');if(d.GX!==undefined)setVal('gxVal',fmt(d.GX),' rad/s');if(d.GY!==undefined)setVal('gyVal',fmt(d.GY),' rad/s');if(real){setMode(true);$('lastPacket').textContent='Last telemetry packet: '+new Date().toLocaleTimeString();if(d.MPU==='OK'){$('mpuState').textContent='MPU6050 status: responding';dot('mpuDot','var(--green)');}else{$('mpuState').textContent='Telemetry received; sensor status not included';dot('mpuDot','var(--yellow)');}}}
 function startDemo(){if(realConnected)return;clearInterval(demoTimer);setMode(false);demoTimer=setInterval(()=>{if(realConnected)return;phase+=.13;showData({ROLL:Math.sin(phase)*2.4,PITCH:Math.cos(phase*.7)*1.8,AX:Math.sin(phase*.8)*.18,AY:Math.cos(phase*.9)*.16,GX:Math.sin(phase*1.1)*.03,GY:Math.cos(phase*.9)*.03},false);},500);}
 function parsePacket(s){const out={};s.split(',').forEach(p=>{const i=p.indexOf(':');if(i<1)return;const k=p.slice(0,i).trim().toUpperCase(),v=p.slice(i+1).trim();if(k==='MPU')out[k]=v;else{const n=Number(v);if(v!==''&&Number.isFinite(n))out[k]=n;}});return out;}
 function onTelemetry(e){const text=new TextDecoder().decode(e.target.value);const d=parsePacket(text);if(Object.keys(d).length)showData(d,true);}
 function controls(on){$('connectBtn').disabled=on;$('disconnectBtn').disabled=!on;$('testBtn').disabled=!on;$('stopBtn').disabled=!on;$('minBtn').disabled=!on;}
 async function connectBLE(){if(!navigator.bluetooth){$('bleHelp').textContent='Web Bluetooth is unavailable here. Try a recent Chrome or Edge browser on desktop or Android over HTTPS or localhost.';return;}try{$('connectBtn').disabled=true;$('bleStatus').textContent='Choose VAJRA2-FLIGHT in the device picker…';device=await navigator.bluetooth.requestDevice({filters:[{name:'VAJRA2-FLIGHT'}],optionalServices:[SERVICE_UUID]});device.addEventListener('gattserverdisconnected',disconnected);server=await device.gatt.connect();const service=await server.getPrimaryService(SERVICE_UUID);commandChar=await service.getCharacteristic(COMMAND_UUID);telemetryChar=await service.getCharacteristic(TELEMETRY_UUID);await telemetryChar.startNotifications();telemetryChar.addEventListener('characteristicvaluechanged',onTelemetry);realConnected=true;clearInterval(demoTimer);setMode(true);$('bleStatus').innerHTML='<strong>Connected</strong> · '+(device.name||'VAJRA2-FLIGHT');$('bleHelp').className='notice green';$('bleHelp').textContent='BLE connected. Live data appears only when telemetry packets arrive. Battery voltage is not provided by the current firmware.';dot('bleDot','var(--green)');controls(true);}catch(err){console.error(err);$('bleStatus').textContent='Connection failed or cancelled';$('bleHelp').textContent=err.message||'Check that the flight board is powered and advertising.';dot('bleDot','var(--red)');controls(false);$('connectBtn').disabled=false;}}
 function disconnected(){realConnected=false;server=null;commandChar=null;telemetryChar=null;$('bleStatus').innerHTML='<strong>Disconnected</strong> · demo mode active';dot('bleDot','var(--yellow)');controls(false);$('connectBtn').disabled=false;$('batteryVal').textContent='Unavailable';$('batteryNote').textContent='No voltage sensor data received';$('batteryFill').style.width='0%';startDemo();}
 async function sendCommand(command){if(!realConnected||!commandChar){$('bleHelp').textContent='Not connected. Demo mode never sends motor commands.';return;}try{const bytes=new TextEncoder().encode(command);if(commandChar.writeValueWithResponse)await commandChar.writeValueWithResponse(bytes);else await commandChar.writeValue(bytes);$('bleHelp').className=(command==='STOP'||command==='MIN')?'notice green':'notice red';$('bleHelp').textContent=`Command "${command}" sent. Confirm the physical response; this website cannot guarantee that the ESC stopped.`;}catch(err){$('bleHelp').textContent='Command failed: '+(err.message||'BLE write error');}}
 $('connectBtn').addEventListener('click',connectBLE);$('disconnectBtn').addEventListener('click',()=>{if(device&&device.gatt&&device.gatt.connected)device.gatt.disconnect();else disconnected();});$('testBtn').addEventListener('click',()=>sendCommand('TEST'));$('stopBtn').addEventListener('click',()=>sendCommand('STOP'));$('minBtn').addEventListener('click',()=>sendCommand('MIN'));$('demoBtn').addEventListener('click',()=>{if(realConnected){$('bleHelp').textContent='Disconnect the ESP32-C3 before switching to demo telemetry.';return;}startDemo();});
 if(!navigator.bluetooth)$('bleHelp').textContent='Web Bluetooth is not supported in this browser. The showcase and demo telemetry still work; live BLE needs a supported Chromium browser over HTTPS or localhost.';controls(false);startDemo();
})();
